// ---------------------------------------------------------------------------------------------------------------------
// jsstrings_zh.js
//   This file is the copyrighted property of Tableau Software and is protected by registered patents and other
//   applicable U.S. and international laws and regulations.
//
//   Unlicensed use of the contents of this file is prohibited. Please refer to the NOTICES.txt file for further details.
// ---------------------------------------------------------------------------------------------------------------------
// WARNING: Computer generated file.  Do not hand modify.
// DEPENDS ON: ['codegen\\resx-strings-js.template', u'D:/builds/public-release/public-release.17.1027.2027/workgroup/vqlweb/scriptsharp/src/Resources/Strings/Strings.zh.resx', u'D:/builds/public-release/public-release.17.1027.2027/workgroup/vqlweb/scriptsharp/src/Resources/Strings/Strings.en.resx']

(function(w) {
  var s = {
    AODialogBandTabTitle: "区间",
    AODialogCellScope: "单元格",
    AODialogComputationLabel: "计算",
    AODialogCustomLabelLabel: "自定义标签",
    AODialogDistributionTabTitle: "分布",
    AODialogFactorsLabel: "因子",
    AODialogFromValueLabel: "值 (自)",
    AODialogInstantAnalyticsBandLabel: "重新计算选定数据的区间",
    AODialogInstantAnalyticsLineLabel: "重新计算选定数据的线",
    AODialogLabelLabel: "标签",
    AODialogLineTabTitle: "线",
    AODialogNumberOfTilesLabel: "图块数",
    AODialogPaneScope: "区",
    AODialogPercentOfLabel: "百分比",
    AODialogPercentagesLabel: "百分比",
    AODialogPercentilesLabel: "百分位",
    AODialogQuantiles: "分位数",
    AODialogStandardDeviation: "标准差",
    AODialogTableScope: "表",
    AODialogTitleString: "编辑 {0}",
    AODialogToValueLabel: "值 (至)",
    AODialogValueLabel: "值",
    AccessbilityNotificationButtonDismissLabel: "关闭通知",
    AccessibilityClearSelectionInstructions: "按 ESC 清除任何标记选择。",
    AccessibilityDataVisualizationTitleAttr: "数据可视化",
    AccessibilityScrollSheetTabsLeft: "向左滚动工作表标签",
    AccessibilityScrollSheetTabsRight: "向右滚动工作表标签",
    AccessibilityViewDataDisabled: "未启用对“查看数据”窗口的访问。",
    AccessibilityViewDataInstructions: "若要打开“查看数据”窗口，请按 Control-Shift-Enter。",
    AddDataConnectionAdd: "添加",
    AddDataConnectionCancel: "取消",
    AddDataExplanation: "选择发布的数据源以将其添加到您的工作簿。",
    AddDataLearnMore: "了解更多信息。",
    AddDataLearnToPublish: "了解如何向 Tableau Server 发布数据源。",
    AddDataNoPublishedDataSources: "没有可用的数据源。",
    AddDataNoSearchMatches: "没有数据源与您的搜索词匹配。",
    AddDataPublishRequirements: "若要发布新数据源，您必须是 {0} 的发布者。",
    AddDataSearchBrowseSuggestion: "滚动以浏览可用数据源的列表。",
    AddDataSearchDifferentTermsSuggestion: "使用其他词重试。",
    AddDataSearchSpellingSuggestion: "检查您的拼写。",
    AddDataSearchSuggestions: "搜索建议：",
    AddSubscribers: "添加",
    AddSubscribersHeader: "添加订阅者",
    AliasDialogHasAliasColumn: "有别名",
    AliasDialogMemberColumn: "成员",
    AliasDialogValueColumn: "值(别名)",
    April: "四月",
    AprilShort: "四月",
    AreYouSureCancel: "取消",
    AreYouSureDelete: "删除",
    AreYouSureText: "是否确定?",
    August: "八月",
    AugustShort: "八月",
    AuthAutoRecoveredSessionMessage: "会话的初始工作簿编辑已经恢复。请单击“保存”或“另存为”以保存所有编辑。单击“恢复”以打开保存的工作簿。",
    AuthAutoRecoveredSessionMessageNoPublish: "会话的初始工作簿编辑已经恢复。请单击“恢复”以打开保存的工作簿。",
    AuthAutoRecoveredSessionMessageNoSave: "会话的初始工作簿编辑已经恢复。请单击“另存为”以保存所有编辑。单击“恢复”以打开保存的工作簿。",
    AuthAutoSavedRecoveredMessage: "以前的编辑已自动恢复。单击“恢复”以返回至已保存的工作簿。(来自于自动保存版本。恢复操作未实现。)",
    AuthCardCollapsedTitle: "{0} &middot; {1}",
    AuthCardTitleColumns: "列",
    AuthCardTitleFilters: "筛选器",
    AuthCardTitleMarks: "标记",
    AuthCardTitleMeasureValues: "度量值",
    AuthCardTitlePages: "页面",
    AuthCardTitleRows: "行",
    AuthColorEditingDisabled: "合并图例以在此处编辑颜色或编辑每个单独图例的颜色。",
    AuthColorPaletteAutomatic: "自动",
    AuthColorPaletteLegacy: "已停用",
    AuthColorPaletteMoreColors: "更多颜色...",
    AuthColorPaletteNone: "无",
    AuthColorTransparencyLabel: "不透明度",
    AuthConnectToDataSource: "连接到 {0} 上的数据源",
    AuthCustomHexColorLabel: "自定义颜色",
    AuthDashboardPaneBlankZone: "空白",
    AuthDashboardPaneFloatingButton: "浮动",
    AuthDashboardPaneHorizontalZone: "水平",
    AuthDashboardPaneNewObjects: "新对象:",
    AuthDashboardPaneSheets: "工作表",
    AuthDashboardPaneSize: "大小",
    AuthDashboardPaneTextZone: "文本",
    AuthDashboardPaneTiledButton: "平铺",
    AuthDashboardPaneTitleCheckbox: "显示仪表板标题",
    AuthDashboardPaneVerticalZone: "垂直",
    AuthDashboardPaneWebZone: "网页",
    AuthDashboardPaneZoneObjects: "对象",
    AuthFontFamilyAndSize: "{0} {1}",
    AuthFontListLoading: "正在加载...",
    AuthFormatLineVisibilityAutomatic: "自动",
    AuthFormatLineVisibilityOff: "关",
    AuthFormatLineVisibilityOn: "开",
    AuthFormatSectionCollapse: "更少",
    AuthFormatSectionExpand: "更多",
    AuthIncludeTotalsLabel: "包括合计",
    AuthLeftContentPaneLabel: "内容",
    AuthLeftLayoutPaneLabel: "布局",
    AuthLeftPaneLabelDashboard: "仪表板",
    AuthLeftPaneTabLabelAnalytics: "分析",
    AuthLineAutomaticPreview: "自动",
    AuthLineOffPreview: "关",
    AuthLineSizePixels: "{0} px",
    AuthMarkSizeLabel: "标记大小",
    AuthMarksCardChooseField: "更多字段",
    AuthMarksCardEncodingTooltipBasic: "在此处拖动维度或度量。",
    AuthMarksCardEncodingTooltipOptions: "在此处拖动维度或度量，或者单击获取更多选项。",
    AuthMastheadDone: "完成",
    AuthMastheadDone_Confirm_CanLogin: "是否要保存对工作簿进行的更改？<br><br>您需要登录才能完成保存更改。",
    AuthMastheadDone_Confirm_CanLogin_Confirm: "登录并保存",
    AuthMastheadDone_Confirm_CanLogin_Deny: "不保存",
    AuthMastheadDone_Confirm_CanSave: "是否要保存对工作簿进行的更改？",
    AuthMastheadDone_Confirm_CanSaveAs: "是否要在新的工作簿保存更改？",
    AuthMastheadDone_Confirm_CanSaveAs_Confirm: "保存副本...",
    AuthMastheadDone_Confirm_CanSaveAs_Deny: "不保存",
    AuthMastheadDone_Confirm_CanSave_Confirm: "保存",
    AuthMastheadDone_Confirm_CanSave_Deny: "不保存",
    AuthMastheadDone_Confirm_Title: "保存工作簿",
    AuthMastheadHelp: "帮助",
    AuthMastheadHelpSearch: "搜索支持",
    AuthMastheadLogin: "登录",
    AuthMastheadLogout: "退出",
    AuthMastheadRevert: "恢复",
    AuthMastheadSave: "保存",
    AuthMastheadSaveAs: "另存为",
    AuthMastheadUserPrefs: "用户首选项",
    AuthMenuBarAnalysis: "分析",
    AuthMenuBarDashboard: "仪表板",
    AuthMenuBarData: "数据",
    AuthMenuBarExit: "关闭",
    AuthMenuBarFile: "文件",
    AuthMenuBarFormat: "设置格式",
    AuthMenuBarMap: "地图",
    AuthMenuBarStory: "故事",
    AuthMenuBarWorksheet: "工作表",
    AuthNumberFormatDecimalLabel: "小数位数",
    AuthNumberFormatSeparatorLabel: "包括分隔符",
    AuthNumberFormatTypeAuto: "自动",
    AuthNumberFormatTypeCurrency: "货币",
    AuthNumberFormatTypeLabel: "数字类型",
    AuthNumberFormatTypeNumber: "数字",
    AuthNumberFormatTypePercentage: "百分比",
    AuthNumberFormatTypeScientific: "科学型",
    AuthNumberFormatUnitsBillionsEnglish: "十亿(B)",
    AuthNumberFormatUnitsBillionsStandard: "十亿(G)",
    AuthNumberFormatUnitsLabel: "单位",
    AuthNumberFormatUnitsMillions: "百万(M)",
    AuthNumberFormatUnitsNone: "无",
    AuthNumberFormatUnitsThousands: "千(K)",
    AuthOffLabel: "关",
    AuthOnLabel: "开",
    AuthPillRemove: "移除",
    AuthRenameDataSource: "重命名数据源",
    AuthRenameDatasourceError: "请将数据源重命名为新的唯一名称",
    AuthRenameField: "重命名字段",
    AuthRenameSheet: "重命名工作表",
    AuthRenameSheetError: "请将工作表重命名为新的唯一名称",
    AuthResetTooltip: "重置工具提示",
    AuthReverseColorLabel: "反向",
    AuthSaveButtonCancel: "取消",
    AuthSaveButtonSave: "保存",
    AuthSaveConfirmOverwrite: "{0} 是否覆盖?",
    AuthSaveErrorTitle: "保存时出错",
    AuthSaveLabelEmbedPassword: "嵌入数据源登录信息",
    AuthSaveLabelName: "名称:",
    AuthSaveLabelProject: "项目:",
    AuthSaveLabelShowTabs: "将工作表显示为选项卡",
    AuthSaveTitle: "保存工作簿",
    AuthSaveWorkbookSavedMessage: "工作簿已保存",
    AuthSchemaViewerHeaderData: "数据",
    AuthSchemaViewerHeaderDimensions: "维度",
    AuthSchemaViewerHeaderMeaures: "度量",
    AuthSchemaViewerHeaderParameters: "参数",
    AuthSchemaViewerHeaderSets: "集",
    AuthShowMeApply: "应用",
    AuthShowMeCantApply: "无法应用",
    AuthShowMeMultipleDimensions: "维度",
    AuthShowMeMultipleMeasures: "度量",
    AuthShowMeRecommended: "建议",
    AuthShowMeSingleDimension: "维度",
    AuthShowMeSingleMeasure: "度量",
    AuthSteppedColorLabel: "步骤",
    AuthStepsLabel: "步骤",
    AuthToolbarAddAllSubtotals: "添加所有小计",
    AuthToolbarCellSize: "单元格大小",
    AuthToolbarCellSizeBigger: "增大",
    AuthToolbarCellSizeNarrower: "变窄",
    AuthToolbarCellSizeShorter: "缩短",
    AuthToolbarCellSizeSmaller: "缩小",
    AuthToolbarCellSizeTaller: "增高",
    AuthToolbarCellSizeWider: "加宽",
    AuthToolbarCellTypeSquare: "方形",
    AuthToolbarCellTypeText: "文本",
    AuthToolbarExport: "下载",
    AuthToolbarFont: "字体",
    AuthToolbarFontDecrease: "减小字体大小",
    AuthToolbarFontIncrease: "增大字体大小",
    AuthToolbarFormatWorkbook: "设置工作簿格式",
    AuthToolbarMarkHideLabels: "隐藏标签",
    AuthToolbarMarkShowLabels: "显示标签",
    AuthToolbarPauseUpdates: "暂停更新",
    AuthToolbarRedo: "重做",
    AuthToolbarRemoveAllSubtotals: "移除所有小计",
    AuthToolbarResumeUpdates: "继续更新",
    AuthToolbarShare: "共享",
    AuthToolbarShowColumnGrandTotals: "显示行总计",
    AuthToolbarShowMe: "智能显示",
    AuthToolbarShowRowGrandTotals: "显示列总计",
    AuthToolbarSubscribe: "订阅",
    AuthToolbarSwap: "交换",
    AuthToolbarTotals: "合计",
    AuthToolbarUndo: "撤消",
    AuthToolbarWorksheet: "工作表",
    AuthToolbarZoomLevel: "适合",
    AuthWorkbookFormatPaneClear: "重置为默认值",
    AuthWorkbookFormatPaneClearOne: "清除",
    AuthWorkbookFormatPaneClearTooltip: "将上面的工作簿格式设置重置为其默认设置",
    AuthWorkbookFormatPaneCloseTooltip: "关闭格式设置窗格",
    AuthWorkbookFormatPaneTitle: "设置工作簿格式",
    AuthenticationRequired: "需要身份验证",
    AuthorBylineText: "请参见此作者提供的更多内容",
    AuthoringAutoRecoveredSessionMessage: "已恢复会话的初始工作簿编辑。若要保存所有编辑，请单击“文件”，然后单击“保存”或“另存为”。若要打开保存的工作簿，请单击“文件”，然后单击“恢复”。",
    AuthoringAutoRecoveredSessionMessageNoPublish: "已恢复会话的初始工作簿编辑。若要打开保存的工作簿，请单击“文件”，然后单击“恢复”。",
    AuthoringAutoRecoveredSessionMessageNoSave: "已恢复会话的初始工作簿编辑。若要保存所有编辑，请单击“文件”，然后单击“另存为”。若要打开保存的工作簿，请单击文件，然后单击“恢复”。",
    AuthoringAutoSavedRecoveredMessage: "以前的编辑已自动恢复。若要返回至已保存的工作簿，请单击“文件”，然后单击“恢复”。(来自于自动保存版本。恢复操作未实现。)",
    AutomaticDashboardSizeText: "将调整仪表板大小以适合显示仪表板所在的任何屏幕",
    BaseClientAllAxisRanges: "所有轴范围",
    BaseClientAllChanges: "所有更改",
    BaseClientAllFilters: "所有筛选器",
    BaseClientAllSorts: "所有排序",
    BaseClientColumns: "列",
    BaseClientInvalidSheet: "无法显示工作表 \'{0}\' 的视图。该工作表无效。",
    BaseClientRows: "行",
    BaseClientSessionExpiredDialogMessage: "您的查看者会话已过期。您必须刷新浏览器。",
    BaseClientSessionExpiredDialogTitle: "会话已过期",
    BrowserErrorProcessing: "浏览器处理错误",
    BrowserErrorProcessingMessage: "处理服务器响应时出错。",
    CalcEditorAffectedSheets: "受影响的工作表",
    CalcEditorApply: "应用",
    CalcEditorApplyTooltip: "应用(Ctrl+Enter)",
    CalcEditorApplyTooltipMac: "应用(Cmd+Enter)",
    CalcEditorCalcError: "计算包含错误。",
    CalcEditorCalcOk: "计算有效。",
    CalcEditorDependenciesPrefix: "更改此计算可能会更改以下内容:",
    CalcEditorOkButtonTooltip: "应用并关闭",
    ChromeDropdownButtonTooltip: "更多选项",
    ClearAliases: "清除别名",
    ClearAllButtonText: "清除列表",
    CloseDataSourceErrorDialogEpilogue: "确保这些工作表不再使用该数据源，然后重试。",
    CloseDataSourceErrorDialogMessage: "\'{0}\'数据源无法关闭，因为以下工作表正在使用它:",
    CloseDataSourceErrorDialogTitle: "无法关闭数据源",
    CollapseSchemaPane: "单击以折叠",
    CommentingToolbarButtonLabel: "注释",
    ConfirmationButtonConfirm: "是",
    ConfirmationButtonDeny: "否",
    ConfirmationTitle: "确认",
    CreateConnectionOnTableauServer: "在此服务器上",
    CreateConnectionToAFile: "到文件",
    CreateConnectionToDatabase: "在云中",
    CurrentPagePanelShowHistory: "显示历史记录",
    CurrentSubscribers: "当前订阅者",
    CustomPaletteGroupUnselectedNote: "选择了自定义调色板。如果选择其他调色板，您将无法再次为此视图选择此自定义调色板。",
    CustomViewsAddYourOwnCustomView: "添加自己的自定义视图",
    CustomViewsCancel: "取消",
    CustomViewsCannotChangeDefault: "不能将默认设置更改为未列出的自定义视图",
    CustomViewsChangeDefaultTo: "将默认设置更改为“{0}”",
    CustomViewsCurrentDefaultIs: "当前默认设置为“{0}”",
    CustomViewsDialogTitle: "自定义视图",
    CustomViewsDone: "完成",
    CustomViewsManageCustomViews: "管理自定义视图",
    CustomViewsManageHeader: "共享、重命名和删除我的自定义视图",
    CustomViewsMyCustomViews: "我的自定义视图",
    CustomViewsNameYourCustomView: "命名自定义视图",
    CustomViewsOriginalName: "原始名称: \"{0}\"",
    CustomViewsOriginalView: "原始",
    CustomViewsOtherCustomViews: "其他自定义视图",
    CustomViewsRemember: "记住",
    CustomViewsRememberMyChanges: "记住我的更改",
    CustomViewsSelectCustomView: "选择自定义视图",
    CustomViewsStartManage: "管理自定义视图",
    CustomViewsUndo: "撤消",
    CustomViewsUnlistedCustomView: "未列出的自定义视图",
    DSDAuthoringWarning: "稍等...此仪表板具有特定于设备的布局，您在此处所做的更改可能会影响这些布局。为了避免出现问题，请在 Tableau Server 上的页面中下载此工作簿，并改为在 Tableau Desktop 中编辑此仪表板。",
    DashboardAuthZoneHeightDisplay: "高度 {0}",
    DashboardAuthZoneLeftPositionDisplay: "x {0}",
    DashboardAuthZoneTopPositionDisplay: "y {0}",
    DashboardAuthZoneWidthDisplay: "宽度 {0}",
    DashboardAuthoringCustomSizeName: "自定义",
    DashboardAuthoringDeviceLayoutDefault: "默认值",
    DashboardAuthoringDeviceLayoutDesktop: "桌面",
    DashboardAuthoringDeviceLayoutPhone: "电话",
    DashboardAuthoringDeviceLayoutTablet: "平板电脑",
    DashboardAuthoringHeightSpinnerLabel: "高度",
    DashboardAuthoringMaximumSizeLabel: "最大值",
    DashboardAuthoringMinimumSizeLabel: "最小值",
    DashboardAuthoringWidthSpinnerLabel: "宽度",
    DashboardSpacingNone: "无",
    DataAlertCondition: "条件",
    DataAlertCreateButton: "创建通知",
    DataAlertCreateButtonSaving: "正在保存...",
    DataAlertCreateFailure: "未能创建通知。",
    DataAlertCreateSuccess: "已成功创建通知。",
    DataAlertDatasourceError: "无法创建通知，因为此工作簿使用需要密码的数据源。",
    DataAlertDialogTitle: "创建通知",
    DataAlertDialogTitleEditMode: "编辑通知",
    DataAlertErrorDialogTitle: "编辑通知时出错",
    DataAlertErrorDialogViewChanged: "视图“{0}”已更改，您尝试编辑的通知不再有效。",
    DataAlertErrorDialogViewChangedWithSubject: "视图“{0}”已更改，通知“{1}”不再有效。",
    DataAlertInitFailure: "无法生成通知创建对话框。",
    DataAlertLoadForEditFailure: "无法加载数据通知以进行编辑。",
    DataAlertNoSubjectErrorMessage: "输入通知电子邮件的主题",
    DataAlertNoUsersMatchSearch: "没有用户符合此搜索条件",
    DataAlertNotificationInterval: "当条件为真时，发送电子邮件:",
    DataAlertOnConstantThreshold: "发送电子邮件，条件是任何条形的“{0}”:",
    DataAlertOnConstantThreshold2: "发送电子邮件，条件是“{0}”:",
    DataAlertRecipientWithNoEmail: "用户必须在 Tableau 中具有电子邮件地址，然后才能将其添加为接收者",
    DataAlertRecipients: "接收者",
    DataAlertSubject: "主题",
    DataAlertSubjectTemplate: "数据通知 - {0}",
    DataAlertThreshold: "阈值",
    DataAlertThresholdConditionMet: "当前条件为真",
    DataAlertThresholdConditionUnmet: "当前条件不为真",
    DataAlertThresholdErrorDouble: "值必须为数值",
    DataAlertThresholdErrorGeneric: "值必须为数值",
    DataAlertThresholdErrorIntegerInputDouble: "值不能包含小数",
    DataAlertThresholdErrorIntegerInputNonNumeric: "值必须为整数",
    DataAlertUpdateButton: "保存通知",
    DataAlertUpdateFailure: "未能更新通知。",
    DataAlertUpdateSuccess: "已成功更新通知。",
    DataAlertsRecipientsSearchPlaceholder: "接收者姓名或用户名",
    DataGridBooleanFalseKeyword: "伪",
    DataGridBooleanTrueKeyword: "真",
    DataGridCancelButton: "取消",
    DataGridErrorButton: "取消",
    DataGridErrorText: "出现了错误。",
    DataGridNullKeyword: "Null",
    DataGridUpdateButton: "立即更新",
    DataInterpreterDataLoss: "Data Interpreter 移除了一些数据。",
    DataInterpreterDescription: "Data Interpreter 或许可以清理您的 {0} 工作簿。",
    DataInterpreterFinished: "已使用 Data Interpreter 清理",
    DataInterpreterLoading: "正在加载...",
    DataInterpreterReady: "使用 Data Interpreter",
    DataInterpreterUndo: "若要撤消更改，请清除复选框。",
    DataSourceCreationInProgress: "正在创建数据源",
    DataSourceGenericErrorButtonLabel: "重试",
    DataSourceGenericErrorMsg: "无法连接到数据源。",
    DataSourceGenericErrorSubMsg: "请再次尝试连接。如果问题仍然存在，请断开数据源连接并与数据源所有者联系。",
    DataSourceGenericTitle: "数据源错误",
    DataTabConnectionsHeader: "连接",
    DataTabDataGridButtonTooltip: "预览数据源",
    DataTabEditDialogTitle: "联接",
    DataTabEditJoinAddJoinPlaceholder: "添加新的联接子句",
    DataTabEditJoinClauseHeaderTitle: "数据源",
    DataTabEditJoinClauseRemoveTooltip: "删除联接子句",
    DataTabEditJoinDisabledTooltip: "此联接类型不适用于这种连接。",
    DataTabEditJoinFull: "完全外部",
    DataTabEditJoinFullTooltip: "包括两个表中的所有值。没有匹配项的成员将显示为 null。",
    DataTabEditJoinInner: "内部",
    DataTabEditJoinInnerTooltip: "只包含在两个表中具有匹配项的值。",
    DataTabEditJoinLeft: "左侧",
    DataTabEditJoinLeftTooltip: "包括左侧表中的所有成员和右侧表中的所有匹配项。没有匹配项的成员将在右侧显示为 null。",
    DataTabEditJoinRight: "右侧",
    DataTabEditJoinRightTooltip: "包括右侧表中的所有成员和左侧表中的所有匹配项。没有匹配项的成员将在左侧显示为 null。",
    DataTabFilePropertiesCharset: "字符集:",
    DataTabFilePropertiesLocale: "区域设置:",
    DataTabFilePropertiesQualifier: "文本限定符:",
    DataTabFilePropertiesSeparator: "字段分隔符:",
    DataTabLiveExtractLabel: "连接",
    DataTabMetadataGridButtonTooltip: "管理元数据",
    DataTabName: "数据源",
    DataTabQualifierAutomatic: "自动",
    DataTabQualifierNone: "无",
    DataTabSearchContains: "包含",
    DataTabSearchExact: "精确",
    DataTabSearchStartsWith: "开头为",
    DataTabSeparatorComma: "逗号",
    DataTabSeparatorOther: "其他",
    DataTabSeparatorSemicolon: "分号",
    DataTabSeparatorSpace: "空格",
    DataTabSeparatorTab: "制表符",
    DataTabSeparatorVerticalBar: "垂直条",
    DataTabViewDataTooltip: "查看数据",
    December: "十二月",
    DecemberShort: "十二月",
    DeleteSheetWithVizInTooltipDialogButton: "删除工作表",
    DeleteSheetWithVizInTooltipDialogMessage: "此工作表显示在其他工作表的工具提示中。删除此工作表也会将其从那些工具提示中移除。<br><br>是否确实要将其删除?",
    DeleteSheetWithVizInTooltipDialogTitle: "删除工作表",
    DialogButtonCancel: "取消",
    DialogButtonDownload: "下载",
    DialogButtonExport: "生成",
    DialogButtonOK: "确定",
    DialogButtonReset: "重置为原始字段名称",
    DialogNoButtonText: "否",
    DialogYesButtonText: "是",
    DisabledDataTabTooltipDetails: "选择另一个数据源，或者下载此工作簿，然后使用 Tableau Desktop 打开。",
    DisabledDataTabTooltipInfo: "无法从数据源页面中查看当前数据源。",
    DropFieldHintText: "在此处放置字段",
    EditConnectionDialogTitle: "编辑连接",
    EmptyDashboardMessage: "在此处添加工作表",
    EmptyDashboardSubMessage: "从左侧的列表中拖放或双击。",
    EmptyFloatingLayoutMessage: "将工作表拖到此处",
    EnterFullscreen: "全屏",
    ExitFullscreen: "退出全屏",
    ExpandSchemaPane: "单击以展开",
    ExportCrosstabDialogMessage: "已生成交叉表。",
    ExportCrosstabDialogTitle: "下载交叉表",
    ExportDataDialogMessage: "已生成数据。",
    ExportDataDialogTitle: "下载数据",
    ExportImageDialogMessage: "已生成图像。",
    ExportImageDialogTitle: "下载图像",
    February: "二月",
    FebruaryShort: "二月",
    FileUploadButtonCancel: "取消",
    FileUploadButtonCancelUpload: "取消上载",
    FileUploadButtonClose: "关闭",
    FileUploadButtonLess: "更少",
    FileUploadButtonMore: "更多",
    FileUploadButtonRetry: "重试",
    FileUploadButtonSkipPlural: "跳过这些文件并继续",
    FileUploadButtonSkipSingular: "跳过此文件并继续",
    FileUploadErrorInfosCompletedHeader: "已完成",
    FileUploadErrorInfosFailedHeader: "失败",
    FileUploadErrorTitle: "上载失败",
    FileUploadErrorTitleMultiComplete: "上载完成: {0}",
    FileUploadErrorTitleMultiFailed: "上载失败: {0}",
    FileUploadFailureTextPlural: "上载 {0} 个文件失败",
    FileUploadFailureTextSingular: "{0} 上载失败",
    FileUploadFatalErrorUnsupportedFileTypeSubtitle: "Tableau Web 制作当前不支持上载此文件类型",
    FileUploadFatalErrorUnsupportedFileTypeTitle: "不支持的文件类型",
    FileUploadFileTypeAccess: "Access",
    FileUploadFileTypeExcel: "Excel",
    FileUploadFileTypeJson: "JSON 文件",
    FileUploadFileTypeOther: "其他文件",
    FileUploadFileTypeSpatial: "空间文件",
    FileUploadFileTypeStatistical: "统计文件",
    FileUploadFileTypeText: "文本文件",
    FileUploadInstructionsPart1: "将文件拖放到此窗口中，或从计算机中 {0} 该文件。",
    FileUploadInstructionsPart2: "上载",
    FileUploadProgressIndicator: "已上载 {0} {2} 个，共 {1} {2} 个",
    FileUploadTitle: "正在上载文件: {0}",
    Filter: "筛选器",
    FirstEnding: "第 {0}",
    Friday: "星期五",
    FridayShort: "周五",
    FunctionTypeAggregate: "聚合",
    FunctionTypeAll: "全部",
    FunctionTypeClearTooltip: "清除",
    FunctionTypeDate: "日期",
    FunctionTypeLogical: "逻辑",
    FunctionTypeNumber: "数字",
    FunctionTypeSearchHint: "输入要搜索的文本",
    FunctionTypeString: "字符串",
    FunctionTypeTableCalculation: "表计算",
    FunctionTypeType: "类型",
    FunctionTypeUser: "用户",
    GlassPaneLoading: "正在加载...",
    GlassPaneSessionExpired: "会话已过期",
    GlassPaneUpdating: "正在更新...",
    GoToSheet: "转到工作表",
    GotoMyLocationPermissionDeniedError: "Tableau 无权使用您的位置。请检查您的位置设置，然后重试。",
    GotoMyLocationPermissionDeniedUnsecureConnection: "Tableau 无权使用您的位置。请检查您的位置设置，然后验证您是否正在使用安全 (https) 连接。",
    GotoMyLocationPositionUnavailableError: "Tableau 找不到您的位置。请检查 Internet 连接，然后重试。",
    GotoMyLocationTimeoutError: "我们尝试查找您的位置的操作已超时。",
    GotoMyLocationTooltip: "转到我的位置",
    GroupDialogGroupButtonLabel: "分组",
    GroupDialogRenameButtonLabel: "重命名",
    GroupDialogUngroupButtonLabel: "取消分组",
    HelpMenuItemAllHelpTopics: "打开已安装的帮助",
    HelpMenuItemContactSupport: "与支持人员联系",
    HelpMenuItemGetHelpAndSupport: "获取帮助与支持",
    HelpMenuItemWebAuthor1: "谁可以编辑和创建工作簿",
    HelpMenuItemWebAuthor2: "编辑和创建视图",
    HelpMenuItemWebAuthor3: "创建工作簿并生成视图",
    Hour: "小时",
    Hours: "{0} 小时",
    IncludeOtherLabel: "包括“其他”",
    January: "一月",
    JanuaryShort: "一月",
    JoinIndicatorTooltipUnknownError: "未知的联接错误",
    JoinTypeCrossJoin: "交叉联接",
    JoinTypeFullJoin: "完整联接",
    JoinTypeInnerJoin: "内联接",
    JoinTypeLeftJoin: "左联接",
    JoinTypeRightJoin: "右联接",
    July: "七月",
    JulyShort: "七月",
    June: "六月",
    JuneShort: "六月",
    LayoutPaneBackgroundColorTitle: "背景",
    LayoutPaneBorderButtonTitle: "边界",
    LayoutPaneFloatingCheckbox: "浮动",
    LayoutPaneHSizeSpinner: "高",
    LayoutPaneMarginButtonTitle: "外边距",
    LayoutPanePaddingButtonTitle: "内边距",
    LayoutPanePositionSpinnersTitle: "位置",
    LayoutPaneSelectedItemTitle: "选定项",
    LayoutPaneSizeSpinnersTitle: "大小",
    LayoutPaneSpacingAllSidesEqual: "所有方面都相等",
    LayoutPaneSpacingBottom: "底部",
    LayoutPaneSpacingLeft: "左侧",
    LayoutPaneSpacingRight: "右侧",
    LayoutPaneSpacingTop: "顶部",
    LayoutPaneWSizeSpinner: "宽",
    LayoutPaneXPositionSpinner: "x",
    LayoutPaneYPositionSpinner: "y",
    LayoutPaneZoneTitleCheckbox: "显示标题",
    LayoutTreeSectionTitle: "项分层结构",
    LeftPaneDSDWarningMsg: "无法在 Web 上编辑设备布局。若要进行编辑，请在 Tableau Desktop 上打开工作簿。",
    LegacyPaletteUnselectedNote: "已停止使用此调色板。如果选择其他调色板，您将无法再次选择此调色板。",
    Legend: "图例",
    LegendPanelHighlightSelectedItems: "突出显示选定项",
    LinePatternNone: "无",
    LineTypeHeading: "行类型",
    ListLengthFive: "{0}、{1}、{2}、{3} 和 {4}",
    ListLengthFour: "{0}、{1}、{2} 和 {3}",
    ListLengthSeven: "{0}、{1}、{2}、{3}、{4}、{5} 和 {6}",
    ListLengthSix: "{0}、{1}、{2}、{3}、{4} 和 {5}",
    ListLengthThree: "{0}、{1} 和 {2}",
    ListLengthTwo: "{0} 和 {1}",
    LogOnButton: "登录以继续",
    ManageCustomViewsDisabledExplanation: "没有要管理的自定义视图。",
    ManageSubscriptions: "管理",
    MapAutoDrillCheckBox: "启用自动钻取",
    MapFloatingToolbarVizCheckBox: "显示视图工具栏",
    MapGeoSearchVizCheckBox: "显示地图搜索",
    MapOptionsDialogTitle: "地图选项",
    MapOptionsDropDownLabel: "单位:",
    MapOptionsUnitAutomatic: "自动",
    MapOptionsUnitMetric: "公制",
    MapOptionsUnitUS: "美制",
    MapScaleVizibilityCheckBox: "显示地图比例尺",
    MapVizNavCheckBox: "允许平移和缩放",
    MapsSearchViewInitialText: "搜索地图",
    March: "三月",
    MarchShort: "三月",
    May: "五月",
    MayShort: "五月",
    MenuBackButton: "后退",
    MetaDataGrid_ConnectionColor: "连接颜色",
    MetaDataGrid_DataType: "数据类型",
    MetaDataGrid_FieldName: "字段名称",
    MetaDataGrid_RemoteFieldName: "远程字段名称",
    MetaDataGrid_Table: "表",
    Minutes: "{0} 分钟",
    Monday: "星期一",
    MondayShort: "周一",
    NewDataSource: "新建数据源",
    NotificationIntervalDaily: "最多每天一次",
    NotificationIntervalEveryTime: "尽可能频繁",
    NotificationIntervalHourly: "最多每小时一次",
    NotificationIntervalOnlyOnce: "一次 - 首次为真时",
    NotificationIntervalWeekly: "最多每周一次",
    November: "十一月",
    NovemberShort: "十一月",
    NumberEnding: "第 {0}",
    NumericBinsBinSizeLabel: "数据桶大小:",
    NumericBinsCntDLabel: "不同计数:",
    NumericBinsDiffLabel: "差异:",
    NumericBinsFieldNameLabel: "新字段名称: ",
    NumericBinsMaxLabel: "最大值:",
    NumericBinsMinLabel: "最小值:",
    NumericBinsRangeOfValuesLabel: "值范围:",
    October: "十月",
    OctoberShort: "十月",
    OldGroupWarning: "该组是在旧版本的 Tableau 中创建的，无法在计算中使用。 ",
    OldGroupWarningLink: "创建副本。",
    OpenInTableauMobile: "在 Tableau Mobile 中打开",
    OperatorAbove: "高于",
    OperatorAboveOrEqual: "高于或等于",
    OperatorBelow: "低于",
    OperatorBelowOrEqual: "低于或等于",
    OperatorEqual: "等于",
    PanZoomSelectToolsLassoSelectionTooltip: "套索(D)",
    PanZoomSelectToolsPanTooltip: "平移(Shift+拖动)",
    PanZoomSelectToolsRadialSelectionTooltip: "径向(S)",
    PanZoomSelectToolsRectangularSelectionTooltip: "矩形(A)",
    PanZoomSelectToolsZoomAreaTooltip: "缩放区域(Ctrl+Shift+拖动)",
    PanZoomSelectToolsZoomAreaTooltipMac: "缩放区域(Cmd+Shift+拖动)",
    PanZoomSelectToolsZoomHomeTooltip: "缩放主页",
    PanZoomSelectToolsZoomInTooltip: "放大(双击)",
    PanZoomSelectToolsZoomOutTooltip: "缩小(Shift+双击)",
    PdfDialogContentDashboard: "此仪表板",
    PdfDialogContentDashboardSheets: "仪表板中的工作表",
    PdfDialogContentStory: "本故事",
    PdfDialogContentTopSheets: "工作簿中的工作表",
    PdfDialogContentWorksheet: "此工作表",
    PdfDialogImageSize: "图像大小(px)",
    PdfDialogPaperSize: "纸张尺寸",
    PdfDialogScalingLabel: "缩放",
    PdfDialogSectionContent: "内容",
    PdfDialogSectionLayout: "布局",
    PdfDialogSelectSheetToChangePrintScaling: "要下载的工作表",
    PdfDialogThumbnailPageSizeLabel: "页面大小",
    PdfDialogThumbnailScalingLabel: "比例:",
    PdfExportFitHigh: "至多 {0} 高",
    PdfExportFitOneHigh: "至多 1 页高",
    PdfExportFitOneWide: "至多 1 页宽",
    PdfExportFitTwoHigh: "至多 2 页高",
    PdfExportFitTwoWide: "至多 2 页宽",
    PdfExportFitWide: "至多 {0} 宽",
    PdfExportFitWideByHigh: "至多 {0}x{1}",
    PdfExportMessageError: "生成 PDF 时出错!",
    PdfExportMessageErrorPng: "下载 PNG 时出错",
    PdfExportMessageExporting: "正在处理...",
    PdfExportMessageSettings: "正从服务器获取 PDF 设置。",
    PdfExportMessageSettingsError: "错误:未能从服务器中检索 PDF 设置。",
    PdfExportPageOrientationLandscape: "横向",
    PdfExportPageOrientationPortrait: "纵向",
    PdfExportPageOrientationPrinter: "打印机",
    PdfExportPageScaleAuto: "自动",
    PdfExportPageScalePercent: "{0}%",
    PdfExportPageSizeA3: "A3",
    PdfExportPageSizeA4: "A4",
    PdfExportPageSizeA5: "A5",
    PdfExportPageSizeB4: "B4",
    PdfExportPageSizeB5: "B5",
    PdfExportPageSizeExecutive: "行政公文纸",
    PdfExportPageSizeFolio: "对开纸",
    PdfExportPageSizeLedger: "帐簿",
    PdfExportPageSizeLegal: "法律",
    PdfExportPageSizeLetter: "信纸",
    PdfExportPageSizeNote: "便笺",
    PdfExportPageSizeQuarto: "四开",
    PdfExportPageSizeStatement: "报表",
    PdfExportPageSizeTabloid: "新闻稿",
    PdfExportPageSizeUnspecified: "未指定",
    PdfExportTitlePDF: "下载 PDF",
    PdfExportTitlePNG: "下载 PNG",
    PressBackButtonMessage: "使用后退按钮返回到有效视图。",
    PrintPdfDialogContentRequired: "至少选择一个要下载的工作表。",
    PrintPdfDialogMessage: "已生成 PDF 文件。",
    PrintPdfDialogTitle: "下载 PDF",
    QuantitativeColorCenter: "居中",
    QuantitativeColorDialogTitle: "编辑颜色 {0}",
    QuantitativeColorEnableSteps: "渐变颜色",
    QuantitativeColorEnd: "结束",
    QuantitativeColorEndSwatch: "结束颜色，自定义颜色 {0}",
    QuantitativeColorFullColorRange: "使用完整颜色范围",
    QuantitativeColorHideAdvanced: "隐藏高级",
    QuantitativeColorIncludeTotals: "包括合计",
    QuantitativeColorPaletteLabel: "调色板",
    QuantitativeColorReset: "重置",
    QuantitativeColorReverse: "反向",
    QuantitativeColorShowAdvanced: "显示高级",
    QuantitativeColorStart: "开始",
    QuantitativeColorStartSwatch: "开始颜色，自定义颜色 {0}",
    QuantitativeColorSteps: "步骤",
    QuickFilterAll: "(全部)",
    QuickFilterAllValues: "所有值",
    QuickFilterApply: "应用",
    QuickFilterCancel: "取消",
    QuickFilterClearDisabled: "显示所有值",
    QuickFilterClearEnabled: "单击以显示所有值",
    QuickFilterConditionalsCondition: "条件",
    QuickFilterConditionalsLimit: "限制",
    QuickFilterDomainShowFewerValues: "显示更少值",
    QuickFilterDomainShowMoreValues: "显示更多值",
    QuickFilterExclusive: "排他",
    QuickFilterInclusive: "包含",
    QuickFilterMultiSelect: "多个",
    QuickFilterMultipleValues: "(多个值)",
    QuickFilterNoItems: "无项目。",
    QuickFilterNonNullValues: "非空值",
    QuickFilterNone: "(无)",
    QuickFilterOnlyNullValues: "仅空值",
    QuickFilterSearch: "搜索",
    QuickFilterSearchAddItemCtrlEnter: "添加项目(Ctrl+Enter)",
    QuickFilterSearchAddItemEnter: "添加项目(Enter)",
    QuickFilterSearchCancel: "取消搜索",
    QuickFilterSearchClearTooltip: "清除(Esc)",
    QuickFilterSearchCloseTooltip: "关闭(Esc)",
    QuickFilterSearchDataIsCaseSensitive: "数据区分大小写。",
    QuickFilterSearchFoundMatches: "找到 {0} 个匹配项",
    QuickFilterSearchHint: "输入要搜索的文本",
    QuickFilterSearchInvalidDataMemberSingular: "“{0}”不是筛选器的有效成员。",
    QuickFilterSearchInvalidDataMembersDialogTitle: "数据成员无效",
    QuickFilterSearchInvalidDataMembersPlural: "以下值不是筛选器的有效成员:",
    QuickFilterSearchNoMatches: "无匹配项。",
    QuickFilterSearchTooltip: "搜索(Enter)",
    QuickFilterShowContextMenu: "显示快速筛选器上下文菜单",
    QuickFilterShowLargerRange: "显示更大的范围",
    QuickFilterShowSmallerRange: "显示更小的范围",
    QuickFilterSingleSelect: "单个",
    QuickFilterTitleBarExclusive: "{0} (排他)",
    QuickFilterUnknown: "<未知>",
    QuickFilterValuesInRange: "范围中的值",
    QuickFilterValuesInRangeOrNull: "范围中的值或空",
    RedirectToApp: "是否重定向到应用商店?",
    RefLineEditorInputTitle: "值:",
    RefreshDataSourceListLabel: "刷新列表",
    RelDateAnchored_curr_day: "锚点日期",
    RelDateAnchored_curr_hour: "锚点小时",
    RelDateAnchored_curr_minute: "锚点分钟",
    RelDateAnchored_curr_month: "锚点月份",
    RelDateAnchored_curr_quarter: "锚点季度",
    RelDateAnchored_curr_second: "锚点秒",
    RelDateAnchored_curr_week: "锚点周",
    RelDateAnchored_curr_year: "锚点年",
    RelDateAnchored_last_day: "昨天",
    RelDateAnchored_last_hour: "前一小时",
    RelDateAnchored_last_minute: "前一分钟",
    RelDateAnchored_last_month: "前一个月",
    RelDateAnchored_last_quarter: "前一个季度",
    RelDateAnchored_last_second: "前一秒",
    RelDateAnchored_last_week: "前一周",
    RelDateAnchored_last_year: "前一年",
    RelDateAnchored_lastn_day: "前 % 天",
    RelDateAnchored_lastn_hour: "前 % 小时",
    RelDateAnchored_lastn_minute: "前 % 分钟",
    RelDateAnchored_lastn_month: "前 % 个月",
    RelDateAnchored_lastn_quarter: "前 % 个季度",
    RelDateAnchored_lastn_second: "前 % 秒",
    RelDateAnchored_lastn_week: "前 % 周",
    RelDateAnchored_lastn_year: "前 % 年",
    RelDateAnchored_next_day: "明天",
    RelDateAnchored_next_hour: "后一小时",
    RelDateAnchored_next_minute: "后一分钟",
    RelDateAnchored_next_month: "后一个月",
    RelDateAnchored_next_quarter: "后一个季度",
    RelDateAnchored_next_second: "后一秒",
    RelDateAnchored_next_week: "后一周",
    RelDateAnchored_next_year: "后一年",
    RelDateAnchored_nextn_day: "后 % 天",
    RelDateAnchored_nextn_hour: "后 % 小时",
    RelDateAnchored_nextn_minute: "后 % 分钟",
    RelDateAnchored_nextn_month: "后 % 个月",
    RelDateAnchored_nextn_quarter: "后 % 个季度",
    RelDateAnchored_nextn_second: "后 % 秒",
    RelDateAnchored_nextn_week: "后 % 周",
    RelDateAnchored_nextn_year: "后 % 年",
    RelDateAnchored_todate_day: "要锚定的日期",
    RelDateAnchored_todate_hour: "要锚定的小时",
    RelDateAnchored_todate_minute: "要锚定的分钟",
    RelDateAnchored_todate_month: "要锚定的月份",
    RelDateAnchored_todate_quarter: "要锚定的季度",
    RelDateAnchored_todate_second: "要锚定的秒",
    RelDateAnchored_todate_week: "要锚定的周",
    RelDateAnchored_todate_year: "要锚定的年",
    RelDateFilterDays: "天",
    RelDateFilterHours: "小时",
    RelDateFilterMinutes: "分钟",
    RelDateFilterMonths: "月",
    RelDateFilterPreview: "{0} 到 {1}",
    RelDateFilterQuarters: "季度",
    RelDateFilterWeeks: "周",
    RelDateFilterYears: "年",
    RelDatePickerFiveYears: "5 年",
    RelDatePickerFiveYearsAbbrev: "5 年",
    RelDatePickerOneDay: "1 天",
    RelDatePickerOneDayAbbrev: "1 天",
    RelDatePickerOneMonth: "1 个月",
    RelDatePickerOneMonthAbbrev: "1 个月",
    RelDatePickerOneWeek: "1 星期",
    RelDatePickerOneWeekAbbrev: "1 周",
    RelDatePickerOneYear: "1 年",
    RelDatePickerOneYearAbbrev: "1 年",
    RelDatePickerThreeMonths: "3 个月",
    RelDatePickerThreeMonthsAbbrev: "3 个月",
    RelDate_curr_day: "今天",
    RelDate_curr_hour: "本小时",
    RelDate_curr_minute: "本分钟",
    RelDate_curr_month: "本月",
    RelDate_curr_quarter: "本季度",
    RelDate_curr_second: "本秒",
    RelDate_curr_week: "本周",
    RelDate_curr_year: "本年",
    RelDate_last_day: "昨天",
    RelDate_last_hour: "前一小时",
    RelDate_last_minute: "前一分钟",
    RelDate_last_month: "前一个月",
    RelDate_last_quarter: "前一个季度",
    RelDate_last_second: "前一秒",
    RelDate_last_week: "前一周",
    RelDate_last_year: "前一年",
    RelDate_lastn_day: "前 % 天",
    RelDate_lastn_hour: "前 % 小时",
    RelDate_lastn_minute: "前 % 分钟",
    RelDate_lastn_month: "前 % 个月",
    RelDate_lastn_quarter: "前 % 个季度",
    RelDate_lastn_second: "前 % 秒",
    RelDate_lastn_week: "前 % 周",
    RelDate_lastn_year: "前 % 年",
    RelDate_next_day: "明天",
    RelDate_next_hour: "后一小时",
    RelDate_next_minute: "后一分钟",
    RelDate_next_month: "后一个月",
    RelDate_next_quarter: "后一个季度",
    RelDate_next_second: "后一秒",
    RelDate_next_week: "后一周",
    RelDate_next_year: "后一年",
    RelDate_nextn_day: "后 % 天",
    RelDate_nextn_hour: "后 % 小时",
    RelDate_nextn_minute: "后 % 分钟",
    RelDate_nextn_month: "后 % 个月",
    RelDate_nextn_quarter: "后 % 个季度",
    RelDate_nextn_second: "后 % 秒",
    RelDate_nextn_week: "后 % 周",
    RelDate_nextn_year: "后 % 年",
    RelDate_todate_day: "本日迄今",
    RelDate_todate_hour: "本小时迄今",
    RelDate_todate_minute: "本分钟迄今",
    RelDate_todate_month: "本月迄今",
    RelDate_todate_quarter: "本季度迄今",
    RelDate_todate_second: "本秒迄今",
    RelDate_todate_week: "本周迄今",
    RelDate_todate_year: "本年迄今",
    RequestAbortedByBrowser: "浏览器已中止请求",
    RowCountLabel: "行",
    Saturday: "星期六",
    SaturdayShort: "周六",
    SaveIncompleteWorkbookWarning: "发布此工作簿时，并非所有视图都是共享的。保存此工作簿将覆盖原始工作簿，并且会丢失未共享的视图。请考虑改用“另存为”。",
    SaveNoPublishedSheetsBody: "工作簿至少必须有一个发布的工作表才能保存。请右键单击标签以发布工作表。",
    SaveNoPublishedSheetsTitle: "无法保存",
    ScheduleDailyDescription: "每天于 {0}",
    ScheduleEvery30MinutesDescription: "每 30 分钟一次，在小时之后的第 15 分钟和第 45 分钟",
    ScheduleEveryOneHourAtXMinutesPastDescription: "每小时一次，在小时之后的第 {0} 分钟",
    ScheduleEveryOneHourDescription: "每小时",
    ScheduleEveryXHoursStartingAtYDescription: "每 {0} 个小时一次，始于 {1}",
    ScheduleEveryXMinutesDescription: "每 {0} 分钟一次",
    ScheduleHourlyDescription: "每隔 {0} 从 {1} 到 {2}",
    ScheduleMonthlyDescription: "在每月第 {0} 天的 {1}",
    ScheduleMonthlyDescriptionLast: "在每月最后一天的 {0}",
    ScheduleMonthlyDescriptionSecondToLast: "在每月倒数第二天的 {0}",
    ScheduleWeeklyDescription: "每周 {1} 的 {0}",
    SearchResultsNotShownPlural: "未显示 {0} 个结果",
    SearchResultsNotShownSingular: "未显示 1 个结果",
    SearchResultsNotShownZero: "未显示 0 个结果",
    SecondEnding: "第 {0}",
    SecurityBlockedURLActionHeader: "URL 被阻止",
    SecurityBlockedURLActionMessage: "已阻止一个可能不安全的 URL。",
    SelectText: "选择",
    SelectionToolsLockTooltip: "按 Shift 以锁定",
    September: "九月",
    SeptemberShort: "九月",
    SerialScheduleDescription: "{0} - {1}",
    SerialScheduleDescriptionSuffix: "连续(较慢)",
    ServerDataSourceConnectedWorkbooks: "工作簿",
    ServerDataSourceConnectedWorkbooksTooltip: "连接到数据源的工作簿数",
    ServerDataSourceConnectionType: "连接类型",
    ServerDataSourceConnectsTo: "连接到",
    ServerDataSourceConnectsToSeveral: "{0} + {1}",
    ServerDataSourceExtract: "数据提取",
    ServerDataSourceLive: "实时",
    ServerDataSourceLiveOrLastExtract: "实时/上次数据提取时间",
    ServerDataSourceName: "名称",
    ServerDataSourceOwner: "所有者",
    ServerDataSourceProject: "项目",
    ServerDataSourceTotalViews: "视图: 全部",
    ServerErrorGeneral: "与服务器通信时出错({0})。<br>这可能是临时出现的网络问题。请重试该操作。<br>如果这种情况仍然存在，请与系统管理员联系。",
    ServerErrorInvalidJSON: "与服务器通信时出错(JSON 无效)。",
    ServerErrorRejected: "服务器已拒绝请求",
    ServerErrorRejectedMessage: "由于请求错误，服务器无法进行响应。<br>这可能是临时出现的网络问题。请重试该操作。<br>如果这种情况仍然存在，请与系统管理员联系。",
    ServerErrorTitle: "服务器错误",
    ServerErrorUnexpected: "意外服务器错误",
    SessionEndedAlertMessage: "是否要重置视图?",
    SessionEndedAlertTitle: "服务器已结束会话",
    SessionForbiddenActionMsg: "您未被授权执行此动作。",
    SessionForbiddenActionTitle: "禁止的操作",
    SessionUnknownErrorTitle: "未知服务器错误",
    ShareDialogAndroidLinkText: "轻击图标以打开链接",
    ShareDialogDisplayOptions: "显示选项",
    ShareDialogDoneButton: "完成",
    ShareDialogEmail: "电子邮件:",
    ShareDialogEmailHelp: "将链接复制并粘贴到电子邮件中",
    ShareDialogEmailLink: "电子邮件链接",
    ShareDialogEmbed: "嵌入:",
    ShareDialogEmbedCodeTableauText: "了解有关 Tableau 的信息",
    ShareDialogEmbedHelp: "复制并粘贴 HTML 代码以在您的网站中嵌入视图",
    ShareDialogEnterUriForBlogEntry: "输入博客条目的 URI",
    ShareDialogEnterValueBetween: "输入介于 {0} 和 {1} 之间的值",
    ShareDialogHeight: "高度:",
    ShareDialogInvalidHeight: "高度无效。",
    ShareDialogInvalidWidth: "宽度无效。",
    ShareDialogLink: "链接:",
    ShareDialogMobileEmailText: "轻击图标以通过电子邮件发送链接",
    ShareDialogMobileLinkText: "按住图标以访问其他共享选项",
    ShareDialogPleaseEnterIntegerBetween: "请输入介于 {0} 和 {1} 之间的整数",
    ShareDialogShowTabs: "显示选项卡",
    ShareDialogShowToolbar: "显示工具栏",
    ShareDialogTitle: "共享视图",
    ShareDialogUrlForRssLinks: "RSS 链接的 URL:",
    ShareDialogWaitingEmbedMessage: "正在创建自定义嵌入代码...",
    ShareDialogWaitingLinkMessage: "正在创建自定义链接...",
    ShareDialogWidth: "宽度:",
    ShowAliases: "显示别名",
    ShowHiddenFields: "显示隐藏字段",
    SignOutFailedMessage: "未能注销。请重试。",
    SizeLegendTextMarkSwatch: "Abc",
    SnapshotApplicationErrorMessage: "无法将 {0} 中的快照应用于此视图",
    SortAtoZAscending: "A 至 Z 升序",
    SortAtoZAscendingPerTable: "按表 A 至 Z 升序",
    SortDataSourceOrder: "数据源顺序",
    SortFields: "排序字段",
    SortZtoADescending: "Z 至 A 降序",
    SortZtoADescendingPerTable: "按表 Z 至 A 降序",
    SpecialAll: "全部",
    SpecialError: "#错误",
    SpecialManyValues: "*",
    SpecialMissing: "#缺少",
    SpecialNoAccess: "#NoAccess",
    SpecialRagged: "#不规则",
    SpecialSkipped: "#跳过",
    SpecialValuesHeading: "特殊值(例如: NULL)",
    SpecialValuesMarkLabel: "标记",
    SpecialValuesMarksHideBreakLines: "隐藏(断开线)",
    SpecialValuesMarksHideConnectLines: "隐藏(连接线)",
    SpecialValuesMarksShowAtDefaultValue: "在默认值处显示",
    SpecialValuesMarksShowAtIndicator: "在指示器上显示",
    SpecialValuesTextLabel: "文本",
    SpecialValuesTextPlaceholder: "(空白)",
    SpecialWildcard: "通配符",
    StopUsingAsLinkingField: "停止使用 {0} 作为链接字段",
    StoryContentPaneBlankButton: "空白",
    StoryContentPaneDuplicateButton: "复制",
    StoryContentPaneSaveAsNewPointButton: "另存为新的",
    StoryContentPaneTitle: "故事",
    StoryContentShowCaptions: "显示说明",
    StoryContentShowTitles: "显示标题",
    StoryEmptyCaptionText: "添加说明",
    StoryEmptyDashboardStoryPointSubtitle: "将工作表添加到仪表板中。",
    StoryEmptyDashboardStoryPointTitle: "此仪表板为空。",
    StoryEmptyFlipboardSubtitle: "在此添加工作表",
    StoryEmptyFlipboardTitle: "从左侧的列表中双击",
    StoryEmptyWorksheetStoryPointSubtitle: "在工作表中创建可视化项。",
    StoryEmptyWorksheetStoryPointTitle: "此工作表为空。",
    StoryNavigatorStyle: "导航器模式",
    StoryNavigatorTypeCaption: "说明框",
    StoryNavigatorTypeDot: "点",
    StoryNavigatorTypeNumber: "数字",
    StoryNavigatorUpdated: "已更新",
    StoryNewPointSectionTitle: "新建故事点",
    StoryPointDeleteTooltip: "删除",
    StoryPointNavigatorLocationBottom: "底部",
    StoryPointNavigatorLocationTitle: "导航器位置",
    StoryPointNavigatorLocationTop: "顶部",
    StoryPointNavigatorShowArrows: "显示箭头",
    StoryPointRevertTooltip: "恢复",
    StoryPointSaveAsNewTooltip: "另存为新点",
    StoryPointUpdateButton: "更新",
    SubscribeButtonTooltip: "订阅",
    SubscribeCancel: "取消",
    SubscribeContent: "内容:",
    SubscribeEnterAddress: "要接收订阅，请输入您的电子邮件地址。",
    SubscribeFailure: "订阅失败。",
    SubscribeInvalidAddress: "请输入有效的电子邮件地址。 ",
    SubscribeNext: "下一步",
    SubscribeOthers: "订阅其他",
    SubscribeOthersFailed: "无法完成 {0} 位订阅者的订阅。",
    SubscribeOthersSearchPlaceholder: "订阅者姓名或用户名",
    SubscribeOthersSuccess: "已创建 {0} 个订阅。",
    SubscribeSelf: "为我订阅",
    SubscribeSelfLabel: "我要订阅",
    SubscribeSheet: "此工作表",
    SubscribeSubject: "主题:",
    SubscribeSubscribe: "订阅",
    SubscribeSuccess: "订阅已成功保存。",
    SubscribeTitle: "订阅",
    SubscribeTo: "收件人:",
    SubscribeViewsToggleLabel: "订阅",
    SubscribeWorkbook: "工作簿中的工作表",
    SuggestBinSizeButtonText: "建议",
    SumOf: "以下项的总计:",
    Sunday: "星期天",
    SundayShort: "周日",
    TabAuthCategoricalColorEditorAssignPalette: "分配调色板",
    TabAuthCategoricalColorEditorReset: "重置",
    TabAuthCategoricalColorEditorSelectItem: "选择数据项",
    TabAuthCategoricalColorEditorSelectPalette: "选择调色板",
    TabAuthColorEditButton: "编辑颜色...",
    TabAuthColorEditLabel: "颜色",
    TabAuthColorEditLegendButtonTooltip: "编辑颜色...",
    TabAuthColorEditorDialogTitle: "编辑颜色 [{0}]",
    TabAuthMarksColorBorderLabel: "边界",
    TabAuthMarksColorHaloLabel: "光环",
    TabAuthSaveDatasourceConfirmMsg: "保存数据源“{0}”以在服务器上共享使用?",
    TabAuthSaveDatasourceDialogTitle: "确认保存数据源",
    TabAuthSaveDatasourceErrorDialogTitle: "保存数据源错误",
    TabAuthSaveDatasourceNotReplacedSuccessMessage: "数据源“{0}”已保存，但在替换此工作簿的连接时出现问题。",
    TabAuthSaveDatasourceNotReplacedSuccessTitle: "保存和替换数据源",
    TabAuthSaveDatasourceReplaceCheckboxLabel: "更新工作簿以连接到保存的数据源",
    TabAuthSaveDatasourceReplacedSuccessMessage: "已保存您的数据源。",
    TabAuthSaveDatasourceReplacedSuccessTitle: "保存和替换数据源",
    TabAuthSaveDatasourceSuccessDialogTitle: "保存数据源成功",
    TabAuthSaveDatasourceSuccessMessage: "您的数据源已保存。项目设置确定此数据源的“连接到”和其他权限。浏览到“数据源”页面以查看此数据源及其属性。",
    TableCalcAddSecondary: "添加辅助计算",
    TableCalcAtTheLevel: "所在级别",
    TableCalcComputeCompoundedRate: "计算复利率",
    TableCalcComputeTotalAcrossPages: "跨所有页面计算合计",
    TableCalcComputeUsing: "计算依据",
    TableCalcDialogTitle: "表计算",
    TableCalcInvalidRestartEveryField: "<无效>",
    TableCalcMissingSortField: "<缺失>",
    TableCalcNestedCalculations: "嵌套计算",
    TableCalcPrimaryTitle: "主要计算类型",
    TableCalcRelativeTo: "相对于",
    TableCalcRestartingEvery: "重新启动间隔",
    TableCalcSecondaryTitle: "从属计算类型",
    TableCalcShowCalculationAssistance: "显示计算帮助",
    TableCalcSingleTitle: "计算类型",
    TableCalcSortAscending: "升序",
    TableCalcSortAutomatic: "特定维度",
    TableCalcSortCustom: "自定义",
    TableCalcSortDescending: "降序",
    TableCalcSortOrder: "排序顺序",
    TableCalcSpecificDimensions: "特定维度",
    TableCalcVisualStructure: "可视结构",
    TableCalcWindowCurrentValue: "当前值",
    TableCalcWindowNullSetting: "若无足够的值则为空",
    ThirdEnding: "第 {0}",
    Thursday: "星期四",
    ThursdayShort: "周四",
    TimeLimitExceededTitle: "超出会话时间限制",
    TimeLimitExceededWarning: "当前可视化计算已超出会话时间限制。",
    ToolbarAboutTableau: "关于 Tableau",
    ToolbarConnectToDataSource: "添加新的数据源",
    ToolbarCurrentView: "当前视图",
    ToolbarCustomViewsDefault: "{0} (默认)",
    ToolbarCustomViewsDeleteButtonTooltip: "删除此视图",
    ToolbarCustomViewsEmptyPlaceholder: "尚未保存任何内容",
    ToolbarCustomViewsEnterManageButtonText: "管理",
    ToolbarCustomViewsErrorChangingPublicPrivateState: "更新自定义视图上的公共/私有状态时出错。",
    ToolbarCustomViewsErrorDeleting: "删除自定义视图时出错。",
    ToolbarCustomViewsErrorInvalidName: "请输入有效的自定义视图名称。",
    ToolbarCustomViewsErrorRenaming: "重命名自定义视图时出错。",
    ToolbarCustomViewsErrorSavingView: "保存自定义视图时出错。",
    ToolbarCustomViewsErrorSettingDefault: "设置默认自定义视图时出错。",
    ToolbarCustomViewsExitManageButtonText: "完成",
    ToolbarCustomViewsHideViewButtonTooltipWhenPrivate: "此视图是私有视图",
    ToolbarCustomViewsHideViewButtonTooltipWhenPublic: "此视图是公共视图",
    ToolbarCustomViewsMakeItMyDefault: "将其设为我的默认值",
    ToolbarCustomViewsMyViews: "我的视图",
    ToolbarCustomViewsOriginalView: "原始",
    ToolbarCustomViewsOtherViews: "其他视图",
    ToolbarCustomViewsRenameButtonTooltip: "重命名此视图",
    ToolbarCustomViewsRenameUIClearButtonTooltip: "取消",
    ToolbarCustomViewsRenameUIPlaceholderText: "重命名此视图",
    ToolbarCustomViewsSave: "保存",
    ToolbarCustomViewsSaveAreaFillerTextManage: "管理",
    ToolbarCustomViewsSaveAreaFillerTextSelect: "选择自定义视图",
    ToolbarCustomViewsSaveButtonDisabledTitle: "请在文本字段中输入自定义视图的名称。",
    ToolbarCustomViewsSetDefaultButtonTooltip: "将此视图设为您的默认视图",
    ToolbarCustomViewsSetDefaultButtonTooltipWhenCurrent: "这是您的当前默认视图",
    ToolbarCustomViewsShareItWithOthers: "将其公开",
    ToolbarCustomViewsTemplate: "视图: {0}",
    ToolbarCustomViewsViewNamePlaceholder: "为此视图命名",
    ToolbarDisabledCrosstabDownloadExplanation: "无法下载交叉表。",
    ToolbarDisabledDataDownloadExplanation: "无法下载数据。",
    ToolbarDisabledDownloadExplanation: "单击视图以启用数据和交叉表下载",
    ToolbarDisabledPdfImageDownloadExplanation: "Permissions are required to download an Image or PDF.",
    ToolbarDisabledWorkbookDownloadExplanation: "需要权限才能下载工作簿。",
    ToolbarDownload: "下载",
    ToolbarDownloadSelectFormat: "Select your file format.",
    ToolbarEdit: "编辑",
    ToolbarEmbedTitle: "嵌入代码",
    ToolbarEnterFullscreen: "全屏",
    ToolbarExitFullscreen: "退出全屏",
    ToolbarExport: "下载",
    ToolbarExportCrosstab: "交叉表",
    ToolbarExportData: "数据",
    ToolbarExportImage: "图像",
    ToolbarLearnMoreAboutTableau: "Learn more about Tableau",
    ToolbarLearnMoreAboutTableauPublic: "Learn more about Tableau Public",
    ToolbarMoreByAuthor: "此作者提供的更多内容",
    ToolbarMoreInfo: "More Information",
    ToolbarOriginalView: "原始视图",
    ToolbarPauseAutomaticUpdates: "暂停自动更新",
    ToolbarPrintToPdf: "PDF",
    ToolbarPublicAvailablePlatforms: "可用于 {0} 和 {1}",
    ToolbarPublicDownloadLabelMobile: "了解更多信息",
    ToolbarPublicDownloadLabelWeb: "获取应用",
    ToolbarPublicExplanationText: "创建交互式的图表、地图、仪表板和应用。将它们发布到 Web 上的任何地方。任何人都能这样做。而且还免费。",
    ToolbarPublicExplanationTitle: "什么是 Tableau Public?",
    ToolbarRefreshData: "刷新此视图的数据",
    ToolbarResumeAutomaticUpdates: "继续自动更新",
    ToolbarRevertAll: "全部恢复",
    ToolbarSendTitle: "链接",
    ToolbarSetCurrentPage: "设置当前页面",
    ToolbarShare: "共享",
    ToolbarShowPerformanceRecording: "性能",
    ToolbarSubscribeAllView: "整个工作簿",
    ToolbarSubscribeDataPresentCheckbox: "视图为空的情况下不发送",
    ToolbarSubscribeEmailPlaceholder: "电子邮件",
    ToolbarSubscribeSchedule: "计划",
    ToolbarSubscribeSubjectPlaceholder: "主题",
    ToolbarSubscribeSubmitButton: "订阅",
    ToolbarSubscribeSubmitDisabledTitle: "请确保您有有效的计划、电子邮件地址和主题以便进行订阅。",
    ToolbarSubscribeThisView: "此视图",
    ToolbarToggleAutoUpdate: "切换自动更新",
    ToolbarViewCount: "{0} 个视图",
    ToolbarWorkbook: "Tableau 工作簿",
    TooltipPanZoomMessage: "双击可缩放/按住可平移",
    Tuesday: "星期二",
    TuesdayShort: "周二",
    UbertipClearSelection: "清除<br/>选择",
    UbertipCommand1Mobile: "清除<br/>选择",
    UbertipCommand7Mobile: "查看数据",
    UbertipItemsSelected: "项已选择",
    UbertipTooltip_Action_DownMobile: "下钻查询",
    UbertipTooltip_Action_UpMobile: "上钻查询",
    UbertipTooltip_ExcludeMobile: "排除",
    UbertipTooltip_GroupMobile: "组成员",
    UbertipTooltip_KeepOnlyMobile: "只保留",
    UbertipTooltip_SortAscendingMobile: "升序排序",
    UbertipTooltip_SortDescendingMobile: "降序排序",
    UbertipTooltip_SplitMobile: "取消成员分组",
    UbertipTooltip_ViewData: "查看数据",
    UnhandledExceptionMessage: "发生意外错误。如果仍然收到此错误，请与 Tableau Server 管理员联系。<br>会话 ID: {0}<br>{1}",
    UnhandledExceptionTitle: "意外错误",
    UploadBytes: "字节",
    UploadGB: "GB",
    UploadKB: "KB",
    UploadMB: "MB",
    UseAsLinkingField: "将 {0} 用作链接字段",
    UserHasNoEmailAddressWarning: "用户在 Tableau 中没有电子邮件地址",
    VizObjectTypeReferenceLine: "参考线",
    WarningTitle: "警告",
    WebZoneHttpsEmbedHttpAuthoring: "由于服务器正在运行 HTTPS，因此必须使用 https:// 而不是使用 http:// 来指定此网页对象的 URL",
    WebZoneHttpsEmbedHttpView: "无法显示网页对象(URL 必须以 https:// 开头)",
    WebZoneUrlDialogTitle: "编辑 URL",
    Wednesday: "星期三",
    WednesdayShort: "周三",
    WindowTableCalcNextValuesLabel: "后面的值",
    WindowTableCalcPreviousValuesLabel: "前面的值",
    WindowTableCalcSummarizeUsing: "根据以下因素汇总值"
  };

  function replaceAll(s, oldValue, newValue) {
    newValue = (newValue === undefined || newValue === null) ? '' : newValue;
    return s.split(oldValue).join(newValue);
  }

  w.tab = w.tab || {};
  if (!tab.Strings) {
    tab.Strings = {
      noLoc: function(str) { return str; },
      getString: function(strKey) { return typeof (tab.Strings[strKey]) === 'undefined' ? '!' + strKey + '!': tab.Strings[strKey]; }
    };
    for (var key in s) {
      if (s.hasOwnProperty(key)) {
        tab.Strings[key] = function() {
          var k = key, hasParams = /{[^}{]+}/.test(s[k]);
          return hasParams ?
            function() {
              var formattedString = s[k];
              for (var i = 0, len = arguments.length; i < len; i++) {
                formattedString = replaceAll(formattedString, '{' + i + '}', arguments[i]);
              }
              return formattedString;
            } :
            s[k];
        }();
      }
    }
  }
}(window));
